# Change these first
owner: staubi82 # Your GitHub organization or username, where this repository lives
repo: Upptime # The name of this repository

sites:
  - name: OeffWetter
    url: https://Oeffwetter.de
  - name: Wetter-Oeffingen
    url: https://wetter-oeffingen.de
  - name: Oeffingen-Wetter
    url: https://oeffingen-wetter.de
  - name: KWH Wetter (Offline)
    url: http://kwhwetter.de
  - name: Staubile.de
    url: https://staubile.de
  - name: Staubi3D.de
    url: http://staubi3d.de
  - name: Staubi Server (Offline)
    url: http://stbsrv.de
  - name: Github Staubi82
    url: https://github.com/staubi82/
  - name: Printables
    url: https://www.printables.com/de/@Staubi
  - name: Google
    url: https://www.google.de
  - name: Cloudflair DNS
    url: https://one.one.one.one/
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: staubi82.github.io
  baseUrl: /Upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Staubi Status und Betriebszeit**"
  introMessage: Willkommen auf der Statusseite von Staubi. Hier überwachen wir in Echtzeit die Verfügbarkeit und Leistung unserer Dienste. Unsere Daten stammen direkt aus unserem GitHub-Repository. Dank GitHub Actions, Issues und Pages benötigen wir keinen zusätzlichen Server. Bleiben Sie stets informiert über den aktuellen Zustand unserer Services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
